apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: nginx-openshift
  name: nginx-openshift
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nginx-openshift:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/keelson/nginx-openshift
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: centos:centos7
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
